{% set version = "0.6.0" %}

package:
  name: nose-parameterized
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/nose-parameterized/nose-parameterized-{{ version }}.tar.gz
  sha256: d35e677aba2f15135b6b7ea7feb88f792b899492ba5365ec0e269015df5214ce

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - nose_parameterized

about:
  home: https://github.com/wolever/nose-parameterized
  license: BSD 2-Clause
  license_file: LICENSE.txt
  summary: 'Parameterized testing with any Python test framework.'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
